server:
  port: ${PORT_USER_API:8003}
spring:
  application:
    name: api-gateway
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
eureka:
  client:
    service-url:
      defalt-zone: ${EUREKA_URL:http://localhost:8761/eureka}



